import './style.css';
const benefits=[
{id:'sport',category:'bienestar',tag:'BIENESTAR',title:'Gimnasio · SportClub',text:'Una propuesta de descuento en SportClub para sumar actividad física a tu día.',image:'sport.jpg',detail:'Descuento en SportClub',body:'El espacio está preparado para informar el convenio con SportClub. El porcentaje, las sedes adheridas y el procedimiento de acceso deben ser confirmados por la seccional. No hay un descuento vigente anunciado en esta muestra.'},
{id:'estudiantes',category:'educacion',tag:'EDUCACIÓN',title:'Estudiantes universitarios',text:'Beneficio social para estudiantes universitarios. Apostamos a tu futuro.',image:'estudiantes.jpg',detail:'Estudiantes universitarios',body:'Propuesta de beneficio social para estudiantes universitarios. Consultá la documentación requerida, el alcance para afiliados y familiares y los períodos de solicitud. Montos y condiciones pendientes de confirmación.'},
{id:'casamiento',category:'familia',tag:'FAMILIA',title:'Beneficio por casamiento',text:'Acompañamiento por casamiento para celebrar una nueva etapa.',image:'casamiento.jpg',detail:'Beneficio por casamiento',body:'Espacio para informar el beneficio por casamiento. La seccional confirmará la documentación, los plazos de presentación y las condiciones para solicitarlo.'},
{id:'nacimiento',category:'familia',tag:'FAMILIA',title:'Beneficio por nacimiento',text:'Un beneficio por nacimiento para acompañar a tu familia.',image:'nacimiento.jpg',detail:'Beneficio por nacimiento',body:'Propuesta de acompañamiento por nacimiento. Consultá las condiciones de afiliación, documentación y plazos con la seccional antes de presentar una solicitud.'},
{id:'cultura',category:'bienestar',tag:'COMUNIDAD',title:'Cultura y comunidad',text:'Actividades culturales y encuentros para disfrutar en comunidad.',image:'comunidad.jpg',detail:'Cultura y comunidad',body:'Este espacio reunirá actividades culturales, encuentros y propuestas recreativas. Las fechas, cupos y condiciones se publicarán cuando sean confirmadas.'},
{id:'capacitacion',category:'educacion',tag:'FORMACIÓN',title:'Cursos y capacitación',text:'Un espacio para cursos, talleres y nuevas oportunidades de formación.',image:'capacitacion.jpg',detail:'Cursos y talleres',body:'Propuesta de formación para nuestra comunidad. Aquí se publicarán temáticas, modalidades, fechas y canales de inscripción validados por la seccional.'}
];
benefits.splice(4,0,{id:'turismo',category:'turismo',tag:'TURISMO',title:'Turismo y escapadas',text:'Propuestas de descanso y vacaciones para compartir con tu familia.',image:'turismo.jpg',detail:'Turismo UTI',body:'Consultá las propuestas de turismo en su página propia.',href:'/turismo.html'});
const details=Object.fromEntries(benefits.map(b=>[b.id,[b.detail,b.body]]));
Object.assign(details,{turismo:['Tu próximo destino','Propuesta ilustrativa: escapadas a la costa, descanso en las sierras y paisajes de la Patagonia. Las ofertas, alojamientos, tarifas y reservas se incorporarán cuando sean aprobadas. Consultá a la seccional antes de organizar un viaje.'],cartilla:['Cartilla y prestadores','La cartilla oficial y los canales de atención de la obra social están pendientes de confirmación. Este espacio permitirá acceder a prestadores y orientación sobre cobertura.'],afiliacion:['Afiliación y grupo familiar','Acercate a la seccional para consultar sobre afiliación y actualización del grupo familiar. Se incorporarán los formularios y requisitos oficiales cuando sean confirmados.'],tramites:['Autorizaciones y reintegros','Consultá el canal oficial de la obra social para tus autorizaciones y reintegros. Los procedimientos y enlaces se incorporarán luego de su validación.'],derechos:['Orientación laboral','La seccional es un espacio de consulta sobre tu situación laboral. Acercate con tu pregunta para recibir orientación por los canales gremiales oficiales.'],licencias:['Licencias y consultas','Consultá a tu representante gremial sobre licencias y documentación. La información específica se publicará después de ser validada; esta muestra no establece requisitos legales.'],delegados:['Delegados y representación','Este espacio está preparado para incorporar el listado oficial de delegados y sus canales de consulta. Mientras tanto, podés acercarte a la sede de Perú 1567.']});
if(document.querySelector('#benefit-grid')) document.querySelector('#benefit-grid').innerHTML=benefits.map(b=>`<article class="card" data-benefit="${b.id}" data-category="${b.category}"><div class="card-image"><img src="/assets/${b.image}" alt="Imagen ilustrativa: ${b.detail}" loading="lazy"><span>${b.tag}</span></div><div class="card-body"><h3>${b.title}</h3><p>${b.text}</p>${b.href?`<a class="card-action" href="${b.href}">Ver turismo <span>↗</span></a>`:`<button data-detail="${b.id}">Conocé el beneficio <span>↗</span></button>`}</div></article>`).join('');
const news=[['comunidad.jpg','COMUNIDAD','Una seccional más cerca de cada compañero.','Propuesta de novedad institucional para presentar los canales de atención y el trabajo de la seccional. Este artículo es un ejemplo editorial.'],['capacitacion.jpg','FORMACIÓN','Aprender, compartir y seguir creciendo.','Ejemplo de nota sobre futuras oportunidades de formación. Los cursos y sus inscripciones aún no están confirmados.'],['turismo.jpg','TURISMO','Empezá a imaginar tu próximo descanso.','Ejemplo de nota turística. Los destinos, precios y fechas serán informados al aprobarse las propuestas.']];
if(document.querySelector('#news-grid')) document.querySelector('#news-grid').innerHTML=news.map((n,i)=>{details['news'+i]=[n[2],n[3]];return `<article class="news"><img src="/assets/${n[0]}" alt="Fotografía ilustrativa de ${n[1].toLowerCase()}" loading="lazy"><p class="meta">${n[1]} · NOTA DE EJEMPLO</p><h3>${n[2]}</h3><button data-detail="news${i}">Leer la nota ↗</button></article>`}).join('');
const modal=document.querySelector('#detail-modal');
document.addEventListener('click',e=>{const trigger=e.target.closest('[data-detail]');if(trigger){const d=details[trigger.dataset.detail];document.querySelector('#detail-title').textContent=d[0];document.querySelector('#detail-body').textContent=d[1];modal.showModal();}});
document.querySelector('#close-modal').onclick=()=>modal.close();document.querySelector('#modal-contact').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});let count=0;document.querySelectorAll('.card').forEach(card=>{card.hidden=button.dataset.filter!=='todos'&&card.dataset.category!==button.dataset.filter;if(!card.hidden)count++;});document.querySelector('#filter-status').textContent=`${count} beneficios visibles`;});
const menu=document.querySelector('#menu'),nav=document.querySelector('#nav');menu.onclick=()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú');menu.textContent=open?'×':'☰';};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menú');menu.textContent='☰';});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open'))menu.click();});
const nowParts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const val=t=>Number(nowParts.find(p=>p.type===t).value);const today=new Date(val('year'),val('month')-1,val('day'));let month=new Date(today.getFullYear(),today.getMonth(),1);
// Eventos exclusivamente ilustrativos, fijados a octubre de 2026.
const events=[{date:'2026-10-08',time:'17:00',title:'Encuentro de la comunidad',type:'Participación',body:'Actividad de demostración para presentar la agenda de la seccional. Sin convocatoria oficial.'},{date:'2026-10-15',time:'15:00',title:'Taller de orientación gremial',type:'Formación',body:'Taller ilustrativo. Fecha, temario y modalidad pendientes de confirmación.'},{date:'2026-10-24',time:'10:00',title:'Jornada de bienestar',type:'Bienestar',body:'Jornada de ejemplo para mostrar la agenda. No hay inscripciones abiertas.'}];
const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function renderEvents(selected){const list=events.filter(e=>selected?e.date===selected:e.date.startsWith(key(month).slice(0,7)));document.querySelector('#event-list').innerHTML=list.length?list.map(e=>`<article class="event-item"><div class="event-date"><strong>${Number(e.date.slice(-2))}</strong><small>OCT</small></div><div><span class="eyebrow">${e.type.toUpperCase()} · EJEMPLO</span><h3>${e.title}</h3><p>${e.time} h · Sede de la seccional</p><button data-event="${e.date}">Ver detalle y guardar fecha ↗</button></div></article>`).join(''):'<p>No hay actividades publicadas para este mes.</p>';}
function renderCalendar(){document.querySelector('#month-label').textContent=month.toLocaleDateString('es-AR',{month:'long',year:'numeric'});const offset=(month.getDay()+6)%7,days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();document.querySelector('#calendar-days').innerHTML='<span></span>'.repeat(offset)+Array.from({length:days},(_,i)=>{const d=new Date(month.getFullYear(),month.getMonth(),i+1),k=key(d),event=events.find(e=>e.date===k);return event?`<button class="day event ${k===key(today)?'today':''}" data-date="${k}" aria-label="${i+1}: ${event.title}, evento de ejemplo">${i+1}</button>`:`<span class="day ${k===key(today)?'today':''}">${i+1}</span>`}).join('');renderEvents();}
if(document.querySelector('#calendar-days')) { document.querySelector('#prev-month').onclick=()=>{month.setMonth(month.getMonth()-1);renderCalendar();};document.querySelector('#next-month').onclick=()=>{month.setMonth(month.getMonth()+1);renderCalendar();};document.addEventListener('click',e=>{const date=e.target.closest('[data-date]');if(date)renderEvents(date.dataset.date);const ev=e.target.closest('[data-event]');if(ev){const item=events.find(x=>x.date===ev.dataset.event);document.querySelector('#detail-title').textContent=item.title;document.querySelector('#detail-body').textContent=item.body;let download=document.querySelector('#download-event');if(!download){download=document.createElement('button');download.id='download-event';download.className='button';modal.append(download);}download.textContent='Guardar evento de ejemplo (.ics)';download.onclick=()=>{const day=item.date.replaceAll('-','');const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//UTI//Demostracion//ES','BEGIN:VEVENT',`UID:${day}-demo@uti.example`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;VALUE=DATE:${day}`,`SUMMARY:DEMO - ${item.title}`,'DESCRIPTION:Evento ilustrativo sin convocatoria oficial.','LOCATION:Peru 1567 CABA','END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([ics],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='uti-evento-demo.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};modal.showModal();}});modal.addEventListener('close',()=>document.querySelector('#download-event')?.remove());renderCalendar(); } document.querySelector('#year').textContent=today.getFullYear();
if(document.querySelector('#hero-video')) { const video=document.querySelector('#hero-video'),toggle=document.querySelector('#video-toggle');function syncVideo(){toggle.textContent=video.paused?'▶ Reproducir video':'Ⅱ Pausar video';toggle.setAttribute('aria-label',video.paused?'Reproducir video':'Pausar video');}toggle.onclick=async()=>{if(video.paused){try{await video.play();}catch{toggle.textContent='Video no disponible';}}else video.pause();syncVideo();};video.addEventListener('play',syncVideo);video.addEventListener('pause',syncVideo);const reduced=matchMedia('(prefers-reduced-motion: reduce)');if(!reduced.matches&&!navigator.connection?.saveData){video.autoplay=true;video.play().catch(()=>syncVideo());}reduced.addEventListener('change',e=>{if(e.matches)video.pause();});

}

const benefitsToggle=document.querySelector('#benefits-toggle');
const benefitsSubmenu=document.querySelector('#benefits-submenu');
function closeBenefitsMenu(){benefitsSubmenu.hidden=true;benefitsToggle.setAttribute('aria-expanded','false');}
benefitsToggle.addEventListener('click',event=>{const open=benefitsSubmenu.hidden||(event.detail>0&&matchMedia('(hover: hover) and (pointer: fine)').matches);benefitsSubmenu.hidden=!open;benefitsToggle.setAttribute('aria-expanded',String(open));});
document.addEventListener('click',event=>{if(!event.target.closest('.nav-benefits'))closeBenefitsMenu();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!benefitsSubmenu.hidden){closeBenefitsMenu();benefitsToggle.focus();}});
if(['turismo','obra-social'].includes(document.body.dataset.page))document.querySelector('.nav-benefits').classList.add('active-section');

// En equipos con mouse, abrir Beneficios al entrar y conservar el toque en móvil.
const benefitsGroup=document.querySelector('.nav-benefits');
const hoverPointer=matchMedia('(hover: hover) and (pointer: fine)');
let benefitsCloseTimer;
benefitsGroup.addEventListener('pointerenter',()=>{if(!hoverPointer.matches)return;clearTimeout(benefitsCloseTimer);benefitsSubmenu.hidden=false;benefitsToggle.setAttribute('aria-expanded','true');});
benefitsGroup.addEventListener('pointerleave',()=>{if(!hoverPointer.matches)return;clearTimeout(benefitsCloseTimer);benefitsCloseTimer=setTimeout(()=>{if(!benefitsGroup.contains(document.activeElement))closeBenefitsMenu();},180);});
benefitsGroup.addEventListener('focusout',event=>{if(!benefitsGroup.contains(event.relatedTarget)&&!benefitsGroup.matches(':hover'))closeBenefitsMenu();});
